name: Lint

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - release/*
      - landchecks/*
  workflow_dispatch:

# The names of steps that actually test the code should be suffixed with `(nonretryable)`.
# When any other step fails, it's job will be retried once by retryBot.
jobs:
  lintrunner:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout PyTorch
        uses: csarofeen/pytorch/.github/actions/checkout-pytorch@master
        with:
          submodules: false
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: x64
          check-latest: false
          cache: pip
          cache-dependency-path: |
            **/.github/requirements-gha-cache.txt

      - name: Install requirements
        run: |
          pip install -r .github/requirements-gha-cache.txt --user

      - name: Initialize lint dependencies
        run: lintrunner init

      - name: Do build steps necessary for linters
        run: |
          python3 -m tools.linter.clang_tidy.generate_build_files
          python3 -m tools.generate_torch_version --is_debug=false
          python3 -m tools.pyi.gen_pyi \
            --native-functions-path aten/src/ATen/native/native_functions.yaml \
            --tags-path aten/src/ATen/native/tags.yaml \
            --deprecated-functions-path "tools/autograd/deprecated.yaml"

      - name: Run lintrunner on all files (nonretryable)
        run: |
          set +e
          if ! lintrunner --force-color --all-files --tee-json=lint.json; then
              echo ""
              echo -e "\e[1m\e[36mYou can reproduce these results locally by using \`lintrunner\`.\e[0m"
              echo -e "\e[1m\e[36mSee https://github.com/csarofeen/pytorch/wiki/lintrunner for setup instructions.\e[0m"
              exit 1
          fi

      - name: Store annotations
        if: always() && github.event_name == 'pull_request'
        # Don't show this as an error; the above step will have already failed.
        continue-on-error: true
        run: |
          # Use jq to massage the JSON lint output into GitHub Actions workflow commands.
          jq --raw-output \
            '"::\(if .severity == "advice" or .severity == "disabled" then "warning" else .severity end) file=\(.path),line=\(.line),col=\(.char),title=\(.code) \(.name)::" + (.description | gsub("\\n"; "%0A"))' \
            lint.json

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
